import type { PerkOSContracts, PerkOSNetwork } from "./types.js";

const MAINNET_DEPLOYER = "SP2K7PV5NXBNRV510S6DCA6RFMTFHAF3ZPK6ZSXPH";
const TESTNET_DEPLOYER = "ST16EWRC01S1SFWGBP63MW47VY8P3AYFA8VGEBGE5";

export const DEFAULT_DEPLOYMENTS: Readonly<Record<PerkOSNetwork, PerkOSContracts>> = {
  mainnet: {
    agentRegistry: `${MAINNET_DEPLOYER}.agent-registry`,
    stxCommerce: `${MAINNET_DEPLOYER}.agentic-commerce-v2`,
    sbtcCommerce: `${MAINNET_DEPLOYER}.sbtc-commerce`,
    reputationRegistry: `${MAINNET_DEPLOYER}.reputation-registry-v2`,
    sbtcToken: "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token",
    sbtcAssetName: "sbtc-token",
  },
  testnet: {
    agentRegistry: `${TESTNET_DEPLOYER}.agent-registry`,
    stxCommerce: `${TESTNET_DEPLOYER}.agentic-commerce-v2`,
    sbtcCommerce: `${TESTNET_DEPLOYER}.sbtc-commerce`,
    reputationRegistry: `${TESTNET_DEPLOYER}.reputation-registry-v2`,
    sbtcToken: "ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token",
    sbtcAssetName: "sbtc-token",
  },
};

export const JOB_STATUS = {
  0: "open",
  1: "funded",
  2: "submitted",
  3: "completed",
  4: "rejected",
  5: "expired",
  6: "timeout-paid",
} as const;

export const CLARITY_ERROR_MESSAGES: Readonly<Record<number, string>> = {
  100: "Only the registry owner may perform this operation.",
  101: "The caller is not authorized by the agent registry.",
  102: "Agent not found.",
  103: "Agent name is invalid.",
  104: "Agent description is invalid.",
  200: "Only the commerce owner may perform this operation.",
  201: "The caller is not authorized.",
  202: "Job not found.",
  203: "The job is not in the required state.",
  204: "The job has expired.",
  205: "The job budget is invalid.",
  207: "Only the job client may perform this operation.",
  208: "Only the assigned provider may perform this operation.",
  209: "Only the evaluator may perform this operation.",
  210: "The job was already funded.",
  212: "The job description is invalid.",
  213: "Client, provider, and evaluator must be distinct.",
  214: "This rater already rated the job.",
  215: "The rating must be between 1 and 5.",
  216: "The job has not expired.",
  300: "Only the commerce owner may perform this operation.",
  301: "The caller is not authorized.",
  302: "Job not found.",
  303: "The job is not in the required state.",
  304: "The job has expired.",
  305: "The job budget is invalid.",
  307: "Only the job client may perform this operation.",
  308: "Only the assigned provider may perform this operation.",
  309: "Only the evaluator may perform this operation.",
  310: "The job was already funded.",
  311: "The supplied payment token is not the configured sBTC token.",
  312: "The job description is invalid.",
  313: "Client, provider, and evaluator must be distinct.",
  314: "This rater already rated the job.",
  315: "The rating must be between 1 and 5.",
  316: "The job has not expired.",
  400: "Only the reputation registry owner may perform this operation.",
  401: "The caller is not an authorized protocol contract.",
  402: "The rating is invalid.",
  403: "This job was already rated.",
  404: "An agent cannot rate itself.",
  500: "Only the reputation registry owner may perform this operation.",
  501: "The caller is not an authorized protocol contract.",
  502: "The rating is invalid.",
  503: "This job was already rated.",
  504: "An agent cannot rate itself.",
  505: "The job outcome is invalid.",
  506: "The job outcome was already recorded.",
  507: "The job outcome was not found.",
  508: "No ownership transfer is pending.",
  509: "Only the proposed owner may accept ownership.",
  510: "The proposed owner is invalid.",
  600: "Only the commerce owner may perform this operation.",
  601: "The caller is not authorized.",
  602: "Job not found.",
  603: "The job is not in the required state.",
  604: "The job expired before submission.",
  605: "The job budget is invalid.",
  607: "Only the job client may perform this operation.",
  608: "Only the assigned provider may perform this operation.",
  609: "Only the evaluator may perform this operation.",
  610: "The job was already funded.",
  612: "The job description is invalid.",
  613: "Client, provider, and evaluator must be distinct.",
  614: "This rater already rated the job.",
  615: "The rating must be between 1 and 5.",
  616: "The job has not expired.",
  617: "The evaluator review window has closed.",
  618: "The Bitcoin review deadline has not passed.",
  619: "The job has no review deadline.",
  620: "No ownership transfer is pending.",
  621: "Only the proposed owner may accept ownership.",
  622: "The proposed owner is invalid.",
  623: "The job has no pending reputation synchronization.",
  700: "Only the commerce owner may perform this operation.",
  701: "The caller is not authorized.",
  702: "Job not found.",
  703: "The job is not in the required state.",
  704: "The job expired before submission.",
  705: "The job budget is invalid.",
  707: "Only the job client may perform this operation.",
  708: "Only the assigned provider may perform this operation.",
  709: "Only the evaluator may perform this operation.",
  710: "The job was already funded.",
  711: "The supplied token does not match the token pinned to this job.",
  712: "The job description is invalid.",
  713: "Client, provider, and evaluator must be distinct.",
  714: "This rater already rated the job.",
  715: "The rating must be between 1 and 5.",
  716: "The job has not expired.",
  717: "The evaluator review window has closed.",
  718: "The Bitcoin review deadline has not passed.",
  719: "The job has no review deadline.",
  720: "No ownership transfer is pending.",
  721: "Only the proposed owner may accept ownership.",
  722: "The proposed owner is invalid.",
  723: "The job has no pending reputation synchronization.",
  724: "The job has no pinned payment token.",
};
